version: '3'

services:
  php:
    ports:
      - "8095:8081"
    networks:
      docker-compose_spellsmell:
        aliases:
          - 'ss-cryptopro'

networks:
  spellsmell:
    ipam:
      config:
        - subnet: 172.145.0.0/16
  docker-compose_spellsmell:
    external: true
